### ISSUE TITLE
MATCH keyword callbacks

### ISSUE THREAD

**Issue by iamjavaexpert** [predsci/psidash#1]
I am facing some problems in MATCH keyword callbacks. According to our design ,  we can have multiple custom workflows. So if i click on that button workflow summary and all other details should be visible. That i have achieved with pattern matching callbacks.  And i also have to open that function window with selected functions of particular workflow. And whenever someone click on that functions i have to render those graphs. So basically i am using nested match keyword and it is not working properly.  Could you suggest something please ?

**Comment by asher-pembroke** [comment]
I'm looking at this now. If you could include a minimal example of the corresponding layout, that would be helpful. `is_open` is not a valid attribute for `dcc.Tab`, `dcc.Tabs`, `dbc.Tab` or `dbc.Tabs`. The closest thing I could find was `html.Details`, which has an `open` attribute.

**Comment by shahiljoshi** [comment]
here, when i split things in different callbacks

**Comment by iamjavaexpert** [comment]
Thanks @asherp for suggestion ,
But When I splitting things up in multiple callbacks like below,

```
  collapse_workflow:
    input:
      - id:
          type: custom-workflow-btn
          id: MATCH
        attr: n_clicks
    output:
      - id:
          type: custom-workflow-summary
          id: MATCH
        attr: is_open
    callback: callbacks.workflow_callbacks.show_workflow_summary

```
```
open_function_area:
    input:
      - id:
          type: custom-workflow-btn
          id: MATCH
        attr: n_clicks
    output:
      - id:
          type: function-area
          id: MATCH
        attr: style
    callback: callbacks.workflow_callbacks.show_workflow_function
```
when i tried this its not working for the all callbacks its only going for "**show_workflow_summary**" callback but its not calling the other callback  "**show_workflow_function**" that displays functions of clicked workflow .

and i have to make another match for the plotting that is the graph plot according to the checkbox are checked so the problem will come in that also like i mentioned below, 

```
  plot_graph:
    input:
     - id:
          type: workflow-check
          id: MATCH
       attr: checked
    output:
     - id: 
         type: graph-parent
         id: MATCH
       attr: children
    state:
     - id: workflow-list-store
       attr: data

    callback: callbacks.workflow_callbacks.show_graph
```
So could you please suggest something on this?
