### ISSUE TITLE
clientside_callback keyword

### ISSUE THREAD

**Issue by asherp** [predsci/psidash#2]
Currently, one has to manually add callbacks that are run clientside:

```python
app.clientside_callback(
    ClientsideFunction(namespace='dash_midi', function_name='stop'),
    Output('stop-clicks', 'children'),
    Input('stop', 'n_clicks'))
```

It would be great if this could be defined in yaml, like so:

```yaml
choose_category:
   input:
   - id: stop
      attr: n_clicks
   output:
   - id: stop-clicks
      attr: children
   clientside_callback: dash_midi.stop
```

`assets/midi.js` (autoloaded, or add to `external_scripts`):

```js
window.dash_clientside = Object.assign({}, window.dash_clientside, {
    dash_midi: {
        stop: function(n_clicks){
            stop_sequence(); // defined elsewhere
            return n_clicks
        },
    }
})
```
